# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 576db44b5759b3b73e215ea1ad171231078c526f7d8ef679611b9b32b79a8857eaf26706073c973cd2029ac98120f68d7669d148fc90faf1df352f84012b8d8d

test:
  secret_key_base: dc05d0bf224739be936ddcac3dc31471150784c1cfed9ade9bb3cb1473696bca051eadc99ece4450a8d1d449f9135ee2b511709212740aa8361eb0311c0e3da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
